version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: actions/download-artifact
        versions: [">= 4"]
      - dependency-name: actions/upload-artifact
        versions: [">= 4"]
    labels:
      - "Github Actions"