:doctype: book
:listing-caption: Listing
:toc: macro

https://github.com/turing85/advent-of-code-2022/blob/main/LICENSE[image:https://img.shields.io/github/license/turing85/advent-of-code-2022[GitHub]]
https://github.com/turing85/advent-of-code-2022/actions/workflows/build.yml?query=branch%3Amain[image:https://img.shields.io/github/actions/workflow/status/turing85/advent-of-code-2022/build.yml[GitHub Workflow Status]]
https://sonarcloud.io/dashboard?id=turing85_advent-of-code-2022[image:https://sonarcloud.io/api/project_badges/measure?project=turing85_advent-of-code-2022&metric=alert_status[Sonarcloud Status]]
https://sonarcloud.io/dashboard?id=turing85_advent-of-code-2022[image:https://sonarcloud.io/api/project_badges/measure?project=turing85_advent-of-code-2022&metric=coverage[Sonarcloud Status]]

[discrete]
= Advent of Code 2022

toc::[]

These are my implementation of the https://adventofcode.com/2022[Advent of Code 2022].

== Prerequisites

To compile and run the project, JDK in version 17+ is required.

== Daily Challenges as Independent Modules
Each daily challenge is implemented as separate maven module. This leads to some code duplication, but guarantees that the modules are independent. The challenges are not only maven-modules, but java-modules as well.

== Build
To build all challenges and execute the tests, we run the following command:

.Build project (Linux)
[[build-linux]]
[source,bash]
----
./mvnw clean package
----

.Build project (Windows)
[[build-windows]]
[source,cmd]
----
mvnw.cmd clean package
----

We can build a specific challenge by just building the corresponding maven submodule, e.g.:

.Build specific challenge (Linux)
[source,bash]
----
./mvnw --projects day-25 clean package

----

.Build specific challenge (Windows)
[source,cmd]
----
mvnw.cmd --projects day-25 clean package
----

Executing the `package` target generates some documentation for each challenge. For example, test coverage reports can be found in `&lt;module-name&gt;/target/jacoco/index.html`

== Generate Documentation

The repository supports generating documentation by executing

.Generate documentation (Linux)
[source,bash]
----
./mvnw --define skipTests --define disable-formatter site
----

.Generate documentation (Windows)
[source,cmd]
----
mvnw.cmd --define skipTests --define disable-formatter site
----

The generated documentation can then be found under `target/staging/index.html`.

Notice that we have to build the project first (xref:build-linux[Linux], xref:build-windows[windows]), otherwise the documentation will be incomplete.

[#calendar]
== Advent of Code Calendar

[options="header",cols="7*"]
|===
^a| Mon
^a| Thue
^a| Wed
^a| Thu
^a| Fri
^a| Sat
^a| Sun
^a|
^a|
^a|
^a|xref:./day-01/README.adoc[Day 1]
^a|xref:./day-02/README.adoc[Day 2]
^a|xref:./day-03/README.adoc[Day 3]
^a|xref:./day-04/README.adoc[Day 4]
^a|xref:./day-05/README.adoc[Day 5]

^a|xref:./day-06/README.adoc[Day 6]
^a|xref:./day-07/README.adoc[Day 7]
^a|xref:./day-08/README.adoc[Day 8]
^a|xref:./day-09/README.adoc[Day 9]
^a|xref:./day-10/README.adoc[Day 10]

^a|xref:./day-11/README.adoc[Day 11]
^a|xref:./day-12/README.adoc[Day 12]
^a|xref:./day-13/README.adoc[Day 13]
^a|xref:./day-14/README.adoc[Day 14]
^a|xref:./day-15/README.adoc[Day 15]

^a|xref:./day-16/README.adoc[Day 16]
^a|xref:./day-17/README.adoc[Day 17]
^a|xref:./day-18/README.adoc[Day 18]
^a|xref:./day-19/README.adoc[Day 19]
^a|xref:./day-20/README.adoc[Day 20]

^a|xref:./day-21/README.adoc[Day 21]
^a|xref:./day-22/README.adoc[Day 22]
^a|xref:./day-23/README.adoc[Day 23]
^a|xref:./day-24/README.adoc[Day 24]
^a|xref:./day-25/README.adoc[Day 25]
|===

== Contributors ✨

Thanks goes to these wonderful people (https://allcontributors.org/docs/en/emoji-key[emoji key]):

++++
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<table>
  <tbody>
    <tr>
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/turing85"><img src="https://avatars.githubusercontent.com/u/32584495?v=4?s=100" width="100px;" alt="Marco Bungart"/><br /><sub><b>Marco Bungart</b></sub></a><br /><a href="#code-turing85" title="Code">💻</a> <a href="#maintenance-turing85" title="Maintenance">🚧</a> <a href="#infra-turing85" title="Infrastructure (Hosting, Build-Tools, etc)">🚇</a></td>
    </tr>
  </tbody>
</table>

<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
++++

This project follows the https://github.com/all-contributors/all-contributors:[all-contributors] specification. Contributions of any kind welcome!