name: Populate Cache

description: |
  An action to populate the maven cache.

inputs:
  nvd-api-key:
    description: The API key for the NVD database, used by the dependency-check scan plugin
    required: true

runs:
  using: composite

  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 17
      id: setup-java

    - name: Set up Maven 3.9.4
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.4

    - name: Populate Cache
      if: ${{ steps.setup-java.outputs.cache-hit != 'true' }}
      shell: sh
      run: |
        mvn \
          --batch-mode \
          --define nvdApiKey=${{ inputs.nvd-api-key }} \
          go-offline:resolve-dependencies \
          dependency-check:update-only

    - name: Cancel Build
      if: ${{ failure() }}
      uses: andymckay/cancel-action@0.3