name: OWASP Scan

description: |
  An action to run an OWASP scan on a report

inputs:
  download-artifacts:
    description: Whether artifacts (Maven state, compiled classes and JARs) should be downloaded
    default: 'true'
    required: false
  nvd-api-key:
    description: The API key for the NVD database, used by the dependency-check scan plugin
    required: true

runs:
  using: composite

  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: 'maven'
        distribution: 'temurin'
        java-version: 17

    - name: Set up Maven 3.9.4
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.4

    - name: Download Maven State
      uses: actions/download-artifact@v4
      if: ${{ inputs.download-artifacts == 'true' }}
      with:
        pattern: maven-state-*
        merge-multiple: true

    - name: Download Compiled Classes
      uses: actions/download-artifact@v4
      if: ${{ inputs.download-artifacts == 'true' }}
      with:
        pattern: compiled-classes-*
        merge-multiple: true

    - name: Download JARs
      uses: actions/download-artifact@v4
      if: ${{ inputs.download-artifacts == 'true' }}
      with:
        pattern: jars
        merge-multiple: true

    - name: OWASP CVE Scan
      shell: sh
      run: |
        mvn \
          --batch-mode \
          --define ci-owasp \
          --define nvdApiKey=${{ inputs.nvd-api-key }} \
          package \
          dependency-check:aggregate

    - name: Upload OWASP Scan Report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        if-no-files-found: error
        name: owasp-report
        path: '**/target/owasp/*.xml'
        retention-days: 2

    - name: Publish Report
      if: ${{ always() }}
      uses: turing85/publish-report@v2
      with:
        report-list-tests: failed
        report-name: OWASP Scan
        report-path: '**/target/owasp/*.xml'

    - name: Cancel Build
      if: ${{ failure() }}
      uses: andymckay/cancel-action@0.3