name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'turing85/advent-of-code-2022' }}

permissions:
  checks: write
  pull-requests: write

jobs:
  recreate-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: (Re-)create Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          header: reports
          recreate: true
          message: |
            ## 🚦Reports🚦
            Reports will be posted here as they get available.

  generate-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Generate Matrix
        id: generate-matrix
        run: |
          root=$(pwd)
          pom_file=pom.xml
          exclude_package_type=pom
          
          mapfile -t candidates < <(
          find "${root}" -type f -name "${pom_file}" \
            | sed "s|/${pom_file}$||" \
            | sort \
            | uniq)
          
          results=()
          for candidate in "${candidates[@]}"
          do
            pom_packaging=0
            grep --quiet \
              "<packaging>${exclude_package_type}</packaging>" \
              "${candidate}/${pom_file}" \
                || pom_packaging="${?}"
            if [[ "${pom_packaging}" -ne 0 ]]
            then
              results+=("${candidate}")
            fi
          done
          matrix=$( \
            echo "${results[@]}" \
              | tr " " "\n" \
              | sed "s|$(pwd)/||" \
              | jq \
                --raw-input \
                --null-input \
                --compact-output \
                "[ [inputs][] | { \"module\": . } ] | { \"include\": . }")
          echo "matrix=${matrix}" >> "${GITHUB_OUTPUT}"

      - name: Cancel Build
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  populate-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
        id: setup

      - name: Populate Cache
        if: ${{ steps.setup.outputs.cache-hit != 'true' }}
        run: |
          mvn \
            --batch-mode \
            go-offline:resolve-dependencies \
            dependency-check:update-only

      - name: Cancel Build
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  build:
    runs-on: ubuntu-latest

    needs:
      - populate-cache

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build
        run: |
          mvn \
            --batch-mode \
            --define ci-build \
            package

      - name: Upload Maven State
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: maven-state
          path: '**/target/maven-*'
          if-no-files-found: error
          retention-days: 2

      - name: Upload Compiled Classes
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: compiled-classes
          path: '**/target/*classes'
          if-no-files-found: error
          retention-days: 2

      - name: Upload JARs
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: jars
          path: '**/target/*.jar'
          if-no-files-found: error
          retention-days: 2

      - name: Cancel Build
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  test:
    runs-on: ubuntu-latest

    needs:
      - recreate-comment
      - generate-matrix
      - build

    continue-on-error: true

    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Download Maven State
        uses: actions/download-artifact@v3
        with:
          name: maven-state

      - name: Download Compiled Classes
        uses: actions/download-artifact@v3
        with:
          name: compiled-classes

      - name: Download JARs
        uses: actions/download-artifact@v3
        with:
          name: jars

      - name: Test ${{ matrix.module }}
        run: |
          mvn \
            --projects ${{ matrix.module }} \
            --batch-mode \
            --define ci-test \
            package

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: '**/target/surefire-reports/TEST*.xml'
          if-no-files-found: error
          retention-days: 2

      - name: Upload Coverage Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: '**/target/jacoco/**/*.xml'
          if-no-files-found: error
          retention-days: 2

  test-report:
    runs-on: ubuntu-latest

    needs:
      - recreate-comment
      - test

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Download Test Report
        uses: actions/download-artifact@v3
        with:
          name: test-report

      - name: JUnit Test Report
        id: junit-report
        uses: phoenix-actions/test-reporting@v10
        with:
          name: JUnit Test Report
          only-summary: true
          path: '**/target/surefire-reports/TEST*.xml'
          reporter: java-junit

      - name: Update PR status comment on success
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request' && steps.junit-report.conclusion == 'success' }}
        with:
          header: reports
          append: true
          message: |

            <details>
              <summary><h3>🥳 JUnit tests passed</h3></summary>

              |Passed|Failed|Skipped|
              |----------|---------|-----------|
              |✅ ${{ steps.junit-report.outputs.passed }}|❌ ${{ steps.junit-report.outputs.failed }}|⚠️ ${{ steps.junit-report.outputs.skipped }}|

              You can see the JUnit report [here](${{ steps.junit-report.outputs.runHtmlUrl }}).
            </details>

      - name: Update PR status comment on failure
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request' && steps.junit-report.conclusion != 'success' }}
        with:
          header: reports
          append: true
          message: |

            <details>
              <summary><h3>😔 JUnit tests failed</h3></summary>

              |Passed|Failed|Skipped|
              |----------|---------|-----------|
              |✅ ${{ steps.junit-report.outputs.passed }}|❌ ${{ steps.junit-report.outputs.failed }}|⚠️ ${{ steps.junit-report.outputs.skipped }}|

              You can see the JUnit report [here](${{ steps.junit-report.outputs.runHtmlUrl }}).
            </details>

      - name: Cancel Build
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  sonar:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Download Maven State
        uses: actions/download-artifact@v3
        with:
          name: maven-state

      - name: Download Compiled Classes
        uses: actions/download-artifact@v3
        with:
          name: compiled-classes

      - name: Download JARs
        uses: actions/download-artifact@v3
        with:
          name: jars

      - name: Download Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: Sonar Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn \
            --batch-mode \
            --define ci-build \
            --define sonar.sourceEncoding=UTF-8 \
            --define sonar.host.url=https://sonarcloud.io \
            --define sonar.organization=turing85-pure \
            --define sonar.projectKey=turing85_advent-of-code-2022 \
            --define sonar.login=${SONAR_TOKEN} \
            package \
            sonar:sonar

      - name: Cancel Build
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  owasp:
    runs-on: ubuntu-latest

    needs:
      - recreate-comment
      - build

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Download Maven State
        uses: actions/download-artifact@v3
        with:
          name: maven-state

      - name: Download Compiled Classes
        uses: actions/download-artifact@v3
        with:
          name: compiled-classes

      - name: Download JARs
        uses: actions/download-artifact@v3
        with:
          name: jars

      - name: OWASP CVE Check
        run: | 
          mvn \
            --batch-mode \
            --define ci-owasp \
            package \
            dependency-check:aggregate

      - name: OWASP Report
        uses: phoenix-actions/test-reporting@v10
        id: owasp-report
        with:
          name: OWASP Report
          list-tests: failed
          path: '**/target/owasp/*.xml'
          reporter: java-junit

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: owasp-report
          path: '**/target/owasp/*.xml'
          if-no-files-found: error
          retention-days: 2

      - name: Update PR status comment on success
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request' && steps.owasp-report.conclusion == 'success' }}
        with:
          header: reports
          append: true
          message: |

            <details>
              <summary><h3>🥳 OWASP tests passed</h3></summary>

              |Passed|Failed|Skipped|
              |----------|---------|-----------|
              |✅ ${{ steps.owasp-report.outputs.passed }}|❌ ${{ steps.owasp-report.outputs.failed }}|⚠️ ${{ steps.owasp-report.outputs.skipped }}|

              You can see the OWASP report [here](${{ steps.owasp-report.outputs.runHtmlUrl }}).
            </details>

      - name: Update PR status comment on failure
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request' && steps.owasp-report.conclusion != 'success' }}
        with:
          header: reports
          append: true
          message: |

            <details>
              <summary><h3>😔 OWASP tests failed</h3></summary>

              |Passed|Failed|Skipped|
              |----------|---------|-----------|
              |✅ ${{ steps.owasp-report.outputs.passed }}|❌ ${{ steps.owasp-report.outputs.failed }}|⚠️ ${{ steps.owasp-report.outputs.skipped }}|

              You can see the JUnit report [here](${{ steps.owasp-report.outputs.runHtmlUrl }}).
            </details>

      - name: Cancel Build
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3