name: Nightly CVE Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  checks: write

jobs:
  populate-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
        id: setup

      - name: Populate Cache
        if: ${{ steps.setup.outputs.cache-hit != 'true' }}
        run: |
          mvn \
            --batch-mode \
            go-offline:resolve-dependencies \
            dependency-check:update-only

      - name: Cancel Build
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  owasp:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: OWASP CVE Check
        run: |
          mvn \
            --batch-mode \
            --define ci-owasp \
            package \
            dependency-check:aggregate

      - name: OWASP Report
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: OWASP Report
          list-tests: failed
          path: '**/target/owasp/*.xml'
          reporter: java-junit

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: owasp-report
          path: '**/target/owasp/*.xml'
          retention-days: 2

      - name: Cancel Build
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3