name: Nightly CVE Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  actions: write
  checks: write

jobs:
  populate-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Populate Cache
        uses: ./.github/actions/populate-cache
        with:
          nvd-api-key: ${{ secrets.NVD_API_KEY }}

  owasp:
    runs-on: ubuntu-latest

    needs:
      - populate-cache

    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: OWASP Scan
        uses: ./.github/actions/owasp-scan
        with:
          download-artifacts: false
          nvd-api-key: ${{ secrets.NVD_API_KEY }}